config/routes.rb
Rails.application.routes.draw do
  root 'campaigns#index'

  namespace :admins do
    get '/', to: 'campaigns#index'

    resources :users, only: [:create, :index]

    resources :campaigns do
      delete 'multiple_destroy', on: :collection

      member do
        post 'add_user'
        post 'close'
        post 'send_reminder'
        delete 'remove_users'
      end
    end
  end

  resources :campaigns, only: [] do
    member do
      get 'give_feedbacks'
      get 'view_feedbacks'
      post 'update_feedback'
    end
  end

  resources :sessions, only: [:new, :create]
  delete '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
	validates_presence_of :name

	has_many :users, -> { order('participants.created_at desc') }, through: :participants
	has_many :participants, dependent: :destroy
	has_many :feedbacks, dependent: :destroy
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates_presence_of :receiver_id, :giver_id, :campaign_id, :content

  belongs_to :campaign
  belongs_to :receiver, class_name: 'User'
  belongs_to :giver, class_name: 'User'
end

app/models/participant.rb
class Participant < ApplicationRecord
	belongs_to :user
	belongs_to :campaign
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates_presence_of :name
	validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

	has_many :feedbacks, dependent: :destroy, foreign_key: :giver_id
  has_many :feedbacks_to_me, dependent: :destroy, foreign_key: :receiver_id, class_name: Feedback
	has_many :campaigns, through: :participants
	has_many :participants
end

app/controllers/admins/base_controller.rb
module Admins
  class BaseController < ApplicationController
    http_basic_authenticate_with name: 'admin', password: 'secret'

    layout 'layouts/admin'

    def execute
      render_response(find_and_create_service.execute)
    end

    private
    def find_and_create_service
      clazz = "Admins::#{find_module}::#{find_action}".constantize
      clazz.new(params)
    end

    def find_module
      controller_name.camelize
    end

    def find_action
      action_name.camelize
    end

    def render_response(data)
      respond_to do |format|
        format.html { @result = data }
        format.js { @result = data }
      end
    end
  end
end

app/controllers/admins/campaigns_controller.rb
module Admins
  class CampaignsController < BaseController
    before_action :require_open, only: [:edit, :update, :add_user, :remove_users, :close, :send_reminder]
    before_action :execute, except: [:index, :create, :multiple_destroy, :show]

    def index
      respond_to do |format|
        format.html { @result = campaigns }
        format.js { @result = campaigns }
      end
    end

    def show
      campaign
    end

    def create
      campaign ||= Campaign.new(name: params[:name])
      if campaign.save
        redirect_to edit_admins_campaign_path(campaign)
      end
    end

    def edit
    end

    def update
    end

    def add_user
    end

    def multiple_destroy
      respond_to do |format|
        if params[:campaign_ids].present?
          Campaign.where(id: params[:campaign_ids]).destroy_all
        end
        format.js { @result = campaigns }
      end
    end

    def remove_users
    end

    def close
    end

    def send_reminder
    end

    private
    def campaign
      @campaign ||= Campaign.find(params[:id])
    end

    def campaigns
      @campaigns = Campaign.where('name ILIKE ?', "%#{params[:term]}%").order(created_at: :desc).page(params[:page]).per(15)
    end

    def require_open
      redirect_to admins_campaign_path(campaign) unless campaign.is_open
    end
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < BaseController
    def index
      @users = User.all.order(created_at: :desc).page(params[:page]).per(15)
    end

    def create
      user = User.new(user_params)
      if user.save
        redirect_back(fallback_location: '/admins/users')
      end
    end

    private

    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    redirect_to '/sessions/new' unless current_user
  end

  def execute
    render_response(find_and_create_service.execute)
  end

  private
  def find_and_create_service
    clazz = "#{find_module}::#{find_action}".constantize
    clazz.new(params, current_user)
  end

  def find_module
    controller_name.camelize
  end

  def find_action
    action_name.camelize
  end

  def render_response(data)
    respond_to do |format|
      format.html { @result = data }
      format.js { @result = data }
    end
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :require_login
  before_action :authorize, only: [:give_feedbacks, :update_feedback, :view_feedbacks]
  before_action :require_open, only: [:give_feedbacks, :update_feedback]
  before_action :execute, except: [:index]

  def give_feedbacks
  end

  def update_feedback
  end

  def view_feedbacks
  end

  def index
    @campaigns = current_user.campaigns
  end

  private

  def campaign
    @campaign ||= Campaign.find(params[:id])
  end

  def authorize
    redirect_to root_path unless campaign.users.include?(current_user)
  end

  def require_open
    redirect_to root_path unless campaign.is_open
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = 'Invalid account info. Please try again'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_nav(controller)
    controller_name == controller ? 'active' : ''
  end
end

app/views/admins/_navbar.html.erb
<div class="ui teal inverted vertical menu huge">
  <a class="item <%= active_nav('campaigns') %>" href="/admins">
    Campaigns
  </a>
  <a class="item <%= active_nav('users') %>" href="/admins/users">
    Users
  </a>
  <div class="item">
    <div class="ui icon input">
      <%= form_tag '/admins', method: 'get', id: 'search_campaign_form' do %>
        <input name="term" size="18" type="text" placeholder="Search campaign...">
      <% end %>
      <i class="search icon" onclick="submitForm()"></i>
    </div>
  </div>
</div>

<script type="text/javascript">
  function submitForm() {
    $('#search_campaign_form').submit()
  }
</script>

app/views/admins/campaigns/_grid.html.erb
<%= form_tag multiple_destroy_admins_campaigns_path, data: {confirm: 'Are you sure that you want to delete the campaigns? All their feedbacks will be deleted'},
             id: 'form-campaigns-destroy', method: :delete, remote: true do %>
    <table class="ui celled table">
      <thead>
      <tr>
        <th width="20px"></th>
        <th>Name</th>
        <th>Created at</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @result.each do |campaign| %>
          <tr>
            <td>
              <%= check_box_tag 'campaign_ids[]', campaign.id, false, id: "campaign_#{campaign.id}" %>
            </td>
            <td><%= campaign.name %></td>
            <td><%= campaign.created_at.strftime("%d/%m/%Y") %></td>
            <td>
              <% if campaign.is_open %>
                  <a class="ui teal button" href="<%= edit_admins_campaign_path(campaign) %>">Edit</a>
              <% else %>
                  <a class="ui blue button" href="<%= admins_campaign_path(campaign) %>">View</a>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
      <tfoot>
      <tr>
        <th colspan="3">
          <div class="ui right floated pagination" id="pagination">
            <%= paginate @result %>
          </div>
        </th>
      </tr>
      </tfoot>
    </table>
<% end %>

app/views/admins/campaigns/_message.html.erb
<div class="ui negative message" id="message">
  <i class="close icon" onclick="removeMessage()"></i>
  <div class="header">
    <%= @result.message %>
  </div>
</div>

<script>
  function removeMessage() {
    $('#message').remove()
  }
</script>

app/views/admins/campaigns/_new.html.erb
<div class="ui modal small" id="new_campaign_modal">
  <i class="close icon"></i>
  <div class="header">
    Create new campaign
  </div>
  <div class="content">
    <%= form_tag '/admins/campaigns', method: 'post', class: 'ui form', id: 'new_campaign_form', remote: true do %>
      <div class="field">
        <label for="name">Enter new campaign's name</label>
        <input id="name" type="text" name="name"/>
      </div>
      <div class="ui submit button">Submit</div>
      <div class="ui error message"></div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#new_campaign_form').form({
    fields: {
      'name': ['empty']
    }
  })
</script>

app/views/admins/campaigns/_users.html.erb
<%= form_tag remove_users_admins_campaign_path(@result.campaign), data: {confirm: 'Are you sure that you want to remove the accounts?'},
             id: 'form-users-campaign-destroy', method: :delete, remote: true do %>
  <table class="ui single line table">
    <thead>
      <tr>
        <th width="20px"></th>
        <th>Email</th>
        <th>Name</th>
        <th width="50px"><a class="ui red button" onclick="$('#form-users-campaign-destroy').submit()">Delete</a></th>
      </tr>
    </thead>
    <tbody>
      <% @result.users.each do |user| %>
        <tr>
          <td>
            <%= check_box_tag 'user_ids[]', user.id, false, id: "user_#{user.id}" %>
          </td>
          <td><%= user.email %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admins/campaigns/add_user.js.erb
<% if @result.message %>
  $('#error-message').html('<%= j render 'message' %>')
<% else %>
  $('#user-table').html('<%= j render 'users' %>')
  $('#email').val('')
<% end %>

app/views/admins/campaigns/close.js.erb
alert("<%= @result.message %>")
window.location.href = "<%= admins_campaign_path(@result.campaign) %>"

app/views/admins/campaigns/edit.html.erb
<div class="ui left floated vertical segment">
  <h1 class="ui header">Edit Campaigns</h1>
</div>
<div class="ui right floated segment vertical">
  <a class="ui teal button"
     data-remote="true"
     data-method='post'
     data-confirm="Are you sure to send reminder email?"
     href="<%= send_reminder_admins_campaign_path(@result.campaign) %>">
    Send feedback reminder email
  </a>
  <a data-method='post'
     data-remote="true"
     data-confirm="Are you sure? Closed campaign will not accept feedback, cannot be editable and reopened. Mails for informing about this event will be sent."
     class="ui red button"
     href="<%= close_admins_campaign_path(@result.campaign) %>">
    Close
  </a>
</div>

<%= form_for [:admins, @result.campaign], html: { class: 'ui form edit-campaign-form' }, remote: true do |f| %>
  <div class="inline field">
    <label for="name">Name</label>
    <%= f.text_field :name, size: '90' %>
  </div>
  <button type="submit" class="ui button">Save</button>
<% end %>

<%= form_tag add_user_admins_campaign_path(@result.campaign), id: 'campaign-user', class: 'ui form', remote: true do -%>
    <div class="field">
      <label for="email">Enter participant's email</label>
      <div class="inline field">
        <input type="text" name="email" id="email" size="60"/>
        <button class="ui button">Add</button>
      </div>
    </div>
    <div class="ui error message"></div>
    <div id="error-message">
    </div>
<% end -%>

<div id="user-table">
  <%= render 'users' %>
</div>

<script type="text/javascript">
  $('#campaign-user').form({
    fields: {
      'email': ['email']
    }
  })
</script>

app/views/admins/campaigns/index.html.erb
<%= render 'new' %>
<div class="ui left floated vertical segment">
  <h1 class="ui header">Campaigns</h1>
</div>
<div class="ui right floated segment vertical">
  <a class="ui green button" onclick="showNewCampaignModal()">Add</a>
  <a class="ui red button" onclick="$('#form-campaigns-destroy').submit()">Delete</a>
</div>

<div id="campaign-grid">
  <%= render 'grid' %>
</div>

<script>
  function showNewCampaignModal() {
    $('#new_campaign_modal').modal('show')
  }
</script>

app/views/admins/campaigns/multiple_destroy.js.erb
$('#campaign-grid').html('<%= j render 'grid' %>')

app/views/admins/campaigns/remove_users.js.erb
$('#user-table').html('<%= j render 'users' %>')

app/views/admins/campaigns/send_reminder.js.erb
alert("<%= @result.message %>")

app/views/admins/campaigns/show.html.erb
<div class="ui left floated vertical segment">
  <h1 class="ui header"><%= @campaign.name %></h1>
</div>

<h1 class="ui header medium" id="show-campaign-header">Participants</h1>
<table class="ui single line table">
  <thead>
  <tr>
    <th>Email</th>
    <th>Name</th>
  </tr>
  </thead>
  <tbody>
  <% @campaign.users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admins/campaigns/update.js.erb
alert("<%= @result.message %>");

app/views/admins/users/_new.html.erb
<div class="ui modal small" id="new_user_modal">
  <i class="close icon"></i>
  <div class="header">
    Create new account
  </div>
  <div class="content">
    <%= form_for [:admin, User.new], url: '/admins/users', html: {class: 'ui form', id: 'new_user_form'}, remote: true do |f| %>
        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
        <div class="field">
          <%= f.label :name %>
          <%= f.email_field :name %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="ui submit button">Submit</div>
        <div class="ui error message"></div>
        <div class="error_field" id="new_user_error_message"></div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $.fn.form.settings.rules.matchPassword = function() {
    return $('#user_password').val() == $('#user_password_confirmation').val()
  };

  $('#new_user_form').form({
    fields: {
      'user[email]': ['email'],
      'user[name]': ['empty'],
      'user[password]': ['minLength[6]'],
      'user[password_confirmation]': ['matchPassword']
    }
  })
</script>

app/views/admins/users/create.js.erb
$('#new_user_error_message').html('The email has been used').css('display', 'block')

app/views/admins/users/index.html.erb
<%= render 'new' %>
<div class="ui left floated vertical segment">
  <h1 class="ui header">Users</h1>
</div>
<div class="ui right floated segment vertical">
  <a class="ui green button" onclick="showNewUserModal()">Add</a>
</div>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.name %></td>
        </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="3">
        <div class="ui right floated pagination" id="pagination">
          <%= paginate @users %>
        </div>
      </th>
    </tr>
  </tfoot>
</table>

<script>
  function showNewUserModal() {
    $('#new_user_modal').modal('show')
  }
</script>

app/views/campaigns/give_feedbacks.html.erb
<div class="container ui center aligned">
  <div class="ui header huge" id="campaign-name-feedbacks"><%= @result.campaign.name %></div>
  <% @result.users.each do |user| %>
    <%= form_tag update_feedback_campaign_path(@result.campaign), class: 'ui form', remote: true do %>
      <input type="hidden" value="<%= user.id %>" name="receiver_id">
      <div class="fields">
        <div class="four wide field">
          <label><%= user.name %></label>
        </div>
        <div class="ten wide field">
          <textarea name="content" rows="4"><%= user.content %></textarea>
        </div>
        <div class="two wide field">
          <button class="ui button submit" id="feedback-sumbit-btn">Save</button>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/campaigns/index.html.erb
<div class="container ui center aligned">
  <% if @campaigns.count > 0 %>
      <div class="ui header huge" id="campaign-name-feedbacks">Your campaigns</div>
      <table class="ui celled padded table">
        <thead>
        <tr>
          <th>Name</th>
          <th width="18px">Status</th>
          <th width="400px"></th>
        </tr>
        </thead>
        <tbody>
        <% @campaigns.each do |campaign| %>
            <tr>
              <td><%= campaign.name %></td>
              <td>
                <%= campaign.is_open ? 'Open' : 'Close' %>
              </td>
              <td>
                <a class="ui teal button" href="<%= view_feedbacks_campaign_path(campaign) %>">View feedbacks</a>
                <% if campaign.is_open %>
                  <a class="ui blue button" href="<%= give_feedbacks_campaign_path(campaign) %>">Give feedbacks</a>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <div class="ui header large">You have no campaign!</div>
  <% end %>
</div>

app/views/campaigns/update_feedback.js.erb
alert("<%= @result.message %>")

app/views/campaigns/view_feedbacks.html.erb
<div class="container ui center aligned">
  <div class="ui header huge" id="campaign-name-feedbacks"><%= @result.campaign.name %></div>
  <% if @result.users.size > 0 %>
    <table class="ui celled padded table">
      <thead>
      <tr>
        <th>Email</th>
        <th width="150px">Name</th>
        <th>Feedback for you</th>
      </tr>
      </thead>
      <tbody>
      <% @result.users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.name %></td>
          <td><%= user.content %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="ui header large">You got no feedback from others!</div>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peer Review Admin</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui stackable two column grid">
      <div class="four wide column" id="menu-col">
        <%= render 'admins/navbar' %>
      </div>
      <div class="twelve wide column" id="main-col">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peer Review Admin</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <div class="ui container">
      <%= render 'share/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/share/_navbar.html.erb
<div class="ui menu">
  <a class="item" href="/">Peer Review</a>
  <div class="right menu">
    <% if current_user %>
      <a class="item" data-method="delete" href="/logout">Logout</a>
    <% end %>
  </div>
</div>